---
version: "3.3"
services:
  db:
    container_name: "local-wordpress-db"
    image: "mysql:5.7"
    restart: always
    volumes:
      - "./data/mysql:/var/lib/mysql"
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
  wordpress:
    container_name: "local-wordpress"
    depends_on:
      - db
    image: "wordpress:latest"
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./godding:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"
